### REGISTERING A USER
POST https://roommatelink-server-production.up.railway.app/api/auth/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "myPassword123!",
  "password_confirmation": "myPassword123!"
}

### LOGGING IN A USER
POST https://roommatelink-server-production.up.railway.app/api/auth/login
Content-Type: application/json

{
  "email": "rltestmail@yahoo.com",
  "password": "myPassword123!"
}

### RESENDING A VERIFICATION LINK
POST https://roommatelink-server-production.up.railway.app/api/auth/resend-verification
Content-Type: application/json

{
  "email": "tejvirs.baidwan@gmail.com"
}

### REQUESTING A PASSWORD RESET LINK
POST https://roommatelink-server-production.up.railway.app/api/auth/request-reset
Content-Type: application/json

{
  "email": "rltestmail@yahoo.com"
}

### VERIFYING AN OTP CODE
POST https://roommatelink-server-production.up.railway.app/api/auth/verify-reset-otp
Content-Type: application/json

{
  "email": "rltestmail@yahoo.com",
  "otp": "484967"
}

### RESETTING A PASSWORD
POST https://roommatelink-server-production.up.railway.app/api/auth/reset-password
Content-Type: application/json

{
  "userId": "ba9904a3-cb29-4884-a4fe-8d4f75ae0bf0",
  "password": "myPassword124!",
  "password_confirmation": "myPassword124!"
}