### REGISTERING A USER
POST https://roommatelink-server-production.up.railway.app/api/auth/register
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "myPassword123!",
  "password_confirmation": "myPassword123!"
}

### LOGGING IN A USER
POST https://roommatelink-server-production.up.railway.app/api/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "myPassword123!"
}